Repository goormthon-Univ/2024_BEOTKKOTTHON_TEAM_18_FE, pull requests merged in 2024-03, with the labels that each got.

#3 🎉 Init(#1): 커밋 메시지 컨벤션 린트 시스템 적용
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package.json
  pnpm-lock.yaml
Labels: Feat

#8 ✨ Feature: TS + Tailwind CSS + shadcn-ui 설정
  components.json
  index.html
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.tsx
  src/index.css
  src/lib/utils.ts
  src/main.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/routes/Layout.tsx
  src/routes/router.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.js
  vite.config.ts
Labels: Feat

#15 ✨ Feat(#5): input, 버튼 컴포넌트 구현
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/components/common/button.tsx
  src/components/common/input.tsx
  src/lib/utils.ts
Labels: Fix, Feat

#17 💄 Style(#14): button, input 컴포넌트 스타일 조정
  src/components/common/Button.tsx
  src/components/common/Input.tsx
Labels: Fix, Style

#23 ✨ Feature: 모집중인 / 참여중인 띱 더보기, 띱 상세보기 페이지 구현
  package.json
  pnpm-lock.yaml
  public/assets/images/commentButtonIcon.svg
  src/components/Home/RecruitingCarousel.tsx
  src/components/Home/SectionHeader.tsx
  src/components/common/Input.tsx
  src/components/icons/CommentButtonIcon.tsx
  src/components/icons/index.js
  src/pages/Ddeep/DdeepDetail.tsx
  src/pages/Ddeep/DdeepMoreParticipating.tsx
  src/pages/Ddeep/DdeepMoreRecruiting.tsx
  src/pages/Home/index.tsx
  src/routes/HFLayout.tsx
  src/routes/HLayout.tsx
  src/routes/PageRouter.tsx
  tailwind.config.js
Labels: Style, Feat

#25 ✨ Feature: 회원가입 페이지 구현
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/pages/Login/index.tsx
  src/pages/SignUp/index.tsx
  src/routes/PageRouter.tsx
  src/schemas/signupSchema.ts
Labels: Feat

#24 ✨ Feature: 알림 페이지 구현
  public/assets/images/messageIcon.svg
  public/assets/images/notificationIcon.svg
  src/components/common/Footer.tsx
  src/components/icons/MessageIcon.tsx
  src/components/icons/NotificationIcon.tsx
  src/components/icons/index.js
  src/constants/footerLabelPathInfo.ts
  src/constants/index.ts
  src/pages/Message/index.tsx
  src/pages/Notification/index.tsx
  src/routes/PageRouter.tsx
Labels: Style, Feat

#27 ✨ Feature: 서버 연동 작업 마무리
  package.json
  pnpm-lock.yaml
  src/apis/cancelDdeep.ts
  src/apis/checkIdValid.ts
  src/apis/checkNicknameValid.ts
  src/apis/createComment.ts
  src/apis/createDdeep.ts
  src/apis/deleteNotification.ts
  src/apis/doneDdeep.ts
  src/apis/enterDdeep.ts
  src/apis/getDdeepDetail.ts
  src/apis/getDdeepList.ts
  src/apis/getHomeParticipatingDdeep.ts
  src/apis/getHomeRecruitingDdeep.ts
  src/apis/getNotificationList.ts
  src/apis/index.ts
  src/apis/leaveDdeep.ts
  src/apis/postLogin.ts
  src/apis/postSignup.ts
  src/components/Home/ParticipatingCarousel.tsx
  src/components/Home/RecruitingCarousel.tsx
  src/components/common/Button.tsx
  src/components/common/Footer.tsx
  src/components/common/FooterElement.tsx
  src/components/common/Input.tsx
  src/components/common/LoginAlertDialog.tsx
  src/components/ui/alert-dialog.tsx
  src/lib/queryClient.ts
  src/main.tsx
  src/pages/Ddeep/DdeepCreate.tsx
  src/pages/Ddeep/DdeepDetail.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/Notification/index.tsx
  src/pages/SignUp/index.tsx
  src/routes/PageRouter.tsx
  src/schemas/createDdeepSchema.ts
  src/schemas/signupSchema.ts
  src/store/tokenStore.ts
  src/types/index.ts
Labels: Fix, Feat
